### ISSUE TITLE
Pre-2.0 API review

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#141]
This issue is effectively a placeholder for notes in API review. We'll close it when we've reviewed the whole API.

**Comment by jskeet** [comment]
# Main package review

Core namespace:
- MimeUtilities naming is inconsistent (ToContentType, CreateContentTypeOrNull, ToMediaTypeHeaderValue)

Extensions namespace:
- DistributedTracing: remove? (See #125)
- Sequence extension methods: GetSequenceString to GetRawSequenceValue?

Http namespace:
- Rename HttpClientExtension to HttpClientExtensions? Note: these aren't extensions on HttpClient itself, but on HttpClient-related types. Could split into separate types if necessary.
  - Incomplete HttpClient functionality: we don't currently have ways of creating requests/responses from events
- Incomplete HttpContent functionality: we don't currently have ways of parsing HttpContent to CloudEvent (only request/response)
- If we keep HttpClientExtensions, should the HttpContent extension methods be merged into that?
- HttpUtilities
  - Rename?
  - Make constant strings public static readonly?
  - GetAttributeNameFromHeaderName: no param description or null validation
- HttpWebExtensions
  - Incomplete functionality: support HttpWebResponse as well?

CloudEvent:
- MediaType... does this have to be const? Are we happy for it to be const? Should it actually be in MimeUtilities?
- Should we implement `IDictionary<string, object>` and/or `IDictionary<CloudEventAttribute, object>`? Doing so later could affect overload resolution, but would be fairly reasonable as a minor version bump. Proposal: leave for now.
- GetPopulatedAttributes() - should we preserve order, or guarantee alphabetical order, or explicitly not guarantee anything? (Stability is nice...)

CloudEventAttributeType:
- Clarifying the validation responsibilities would be nice, but doesn't block 2.0. It's not like anyone else can add more attributes.
- Expose the generic type? Probably not worth it.

CloudEventFormatter:
- Everything is done in terms of `byte[]`. If we want to use `Memory<byte>` or similar, we need to do that now.
- Still not hugely happy with the separation of concerns, but I'm not sure there's much we can do. I haven't come up with any better ideas.
- Might want to provide more centralized handling (see #127) but that can be done in a non-breaking way.
- Incomplete functionality: no introspection ("Do you support this format type? Can you encode this data?"). Designing this properly would probably take a long time, and is hard without experience of use cases... although adding it to an abstract class later without breaking will be tricky. Proposal: reluctantly defer.

CloudEventsSpecVersion
- There's a comment suggesting renaming to CloudEventSpecVersion. I've become more convinced that it's correct and okay as it is. (And it won't be used by very much code.) Proposal: delete the comment.

ContentMode (the enum of binary/structured; does *not* include batch)
- Bit ugly, but probably okay.

**Comment by jskeet** [comment]
# AMQP review

- AmqpClientExtensions: rename to AmqpExtensions?

# ASP.NET Core review

- CloudEventJsonInputFormatter has two FIXMEs, and is generally not something I'm massively familiar with. Proposal: remove from 2.0.0, but aim to reintroduce at some point.
- HttpRequestExtensions
  - Missing functionality: CopyToHttpRequest?
- Missing functionality: HttpResponseExtensions? (In particular, CopyToHttpResponse)

# Avro review

- AvroEventFormatter is not sealed, and doesn't have any new virtual methods... probably okay though? Could potentially create an `AvroEventFormatter<T>` that attempts to deserialize the data, and use a virtual method in `AvroEventFormatter` for that.
  - No binary format support. I think this is reasonable.

# Kafka review

- KafkaClientExtensions: Rename to KafkaExtensions?

# MQTT review

- MqttClientExtensions: rename to MqttExtensions?
- Currently no support for binary mode: need a newer version of MQTTnet

# JSON event format review (both packages)

- Seem okay

**Comment by JoshLove-msft** [comment]
> CloudEvent: 
MediaType... does this have to be const? Are we happy for it to be const? Should it actually be in MimeUtilities?

I think it should probably be in MimeUtilities - that way it will live next to the Batch media type.

> Should we implement IDictionary<string, object> and/or IDictionary<CloudEventAttribute, object>? Doing so later could affect overload resolution, but would be fairly reasonable as a minor version bump. Proposal: leave for now.

I think a more useful API would be GetPopulatedExtensionAttributes that behaves like GetPopulatedAttributes (but for extensions only). I would think it would be more common to want to enumerate the extension attributes and their values rather than all attributes and their values. With that in mind, I don't see much benefit to having CloudEvent implement IDictionary though I may be missing some scenario.

> GetPopulatedAttributes() - should we preserve order, or guarantee alphabetical order, or explicitly not guarantee anything? (Stability is nice...)

I would expect this to work similar to the ExtensionAttributes property. I believe that would preserve order?

**Comment by JoshLove-msft** [comment]
> There's a comment suggesting renaming to CloudEventSpecVersion. I've become more convinced that it's correct and okay as it is. (And it won't be used by very much code.) Proposal: delete the comment.

That is probably true that it is technically correct, but I still think it reads oddly and it is inconsistent with the rest of the type naming, but not a big deal either way.

**Comment by JoshLove-msft** [comment]
> Everything is done in terms of byte[]. If we want to use Memory<byte> or similar, we need to do that now.

My vote is to use `ReadOnlyMemory<byte>` as this is more common in new APIs in the BCL.

**Comment by JoshLove-msft** [comment]
> Rename HttpClientExtension to HttpClientExtensions? Note: these aren't extensions on HttpClient itself, but on HttpClient-related types. Could split into separate types if necessary.

Make sense.

> Incomplete HttpClient functionality: we don't currently have ways of creating requests/responses from events

Hmm, I'm not sure how useful that would be considering you would need to set a bunch of other information on the Request/Response messages.

> Incomplete HttpContent functionality: we don't currently have ways of parsing HttpContent to CloudEvent (only request/response)

How would this work for binary mode? Wouldn't you need the response/request headers? Even for structured mode, wouldn't you need to know the content type header?

> If we keep HttpClientExtensions, should the HttpContent extension methods be merged into that?

I think so.

**Comment by JoshLove-msft** [comment]
Agree with removing "Client" from the various protocol extensions.

**Comment by jskeet** [comment]
Agreed to do:

- Move CloudEvent.MediaType into MimeUtilities
- Rename HttpClientExtension to HttpClientExtensions
- Move HttpContentExtensions into HttpClientExtensions
- Not guarantee ordering of attributes yet, but potentially do so in the future
- Not implement GetPopulatedExtensionAttributes *yet*, but consider it in the future
- Not change CloudEventsSpecVersion
- File new issue around populating HttpResponse - show existing code, and we can see whether it needs more help
- Remove client suffixes from extensions

**Comment by jskeet** [comment]
Result of meeting on 2021-05-21 around the "body" parameters:

- `ReadOnlyMemory<byte>` can't easily be transformed into a stream, which is what other APIs need to consume (e.g. for Avro, Protobuf, Json.NET CloudEventFormatters)
- The `BinaryData` type in `System.Memory.Data` would be a good fit, and would handle `ReadOnlyMemory<byte>`, but that brings in a load of other dependencies, including System.Text.Json

We've agreed to keep thinking about it...

**Comment by jskeet** [comment]
Still TBD: what we do with CloudEventJsonInputFormatter - we forgot to discuss that last Friday. @JoshLove-msft are you happy for me to remove it for now?

**Comment by jskeet** [comment]
This is now done.
