### ISSUE TITLE
pass the name parameter to the ArgumentException, instead of nameof(name)

### ISSUE THREAD

**Issue by jamir-araujo** [cloudevents/sdk-csharp#158]
https://github.com/cloudevents/sdk-csharp/blob/506efb4f1ad9a97e9370f08382528404ec3549c6/src/CloudNative.CloudEvents/CloudEventAttribute.cs#L103

https://github.com/cloudevents/sdk-csharp/blob/506efb4f1ad9a97e9370f08382528404ec3549c6/src/CloudNative.CloudEvents/CloudEventAttribute.cs#L111

The way it's now the exception doesn't help to identify which of attributes has an invalid name

**Comment by jskeet** [comment]
The `nameof(name)` part is definitely correct - that's the name of the parameter being validated.

For the first exception, the name is empty, so there's nothing useful to add. For the second, we could change the message:

```csharp
throw new ArgumentException($"Invalid character '{c}' in attribute name '{name}'", nameof(name)); 
```

**Comment by jamir-araujo** [comment]
Adding the name of the attribute on the message will definitely help.
