### ISSUE TITLE
Implement method HttpListenerRequest.ToCloudEventAsync

### ISSUE THREAD

**Issue by rinormaloku** [cloudevents/sdk-csharp#16]
In the docs (the readme) the extension method Request.ToCloudEventAsync() is presented, but it actually doesn't exit.

**Comment by jskeet** [comment]
I believe in the current version (1.3.80) this is [`ReadCloudEventAsync`](https://github.com/cloudevents/sdk-csharp/blob/b0f3c06a5f5d33abf3f5c42a714037490a9afd65/src/CloudNative.CloudEvents.AspNetCore/HttpRequestExtension.cs#L33). I don't know whether the docs are ahead or behind reality.

**Comment by jotatoledo** [comment]
Just bumped against this while trying to consume cloud events from azure event grid in an azure function. Saddly as [stated in the docs](https://docs.microsoft.com/de-de/azure/event-grid/cloudevents-schema#use-with-azure-functions), the event grid binding/trigger for azure fns [does not support this out of the box yet](https://github.com/Azure/azure-functions-eventgrid-extension/issues/84), so I jumped from one issue to the next 😄 

Is this up for picks? I would be happy to submit a PR.

**Comment by jskeet** [comment]
Only just seen this again, nearly a year after initially doing so.

I'm going to try to get some conventions in place for conversions like this - I'd like it to be `ToCloudEventAsync` eventually :)

**Comment by jskeet** [comment]
Note to self: this still isn't done. (Although adding it post-2.0 would not be a breaking change.)
