### ISSUE TITLE
HttpRequest.ToCloudEventAsync only works with version in HTTP header

### ISSUE THREAD

**Issue by tomkerkhove** [cloudevents/sdk-csharp#165]
`HttpRequest.ToCloudEventAsync` only works when the version is in HTTP header (binary mode) and not as part of the payload.

Otherwise, it will throw the following error:
> System.ArgumentException: Unknown CloudEvents spec version '' (Parameter 'httpRequest')
   at CloudNative.CloudEvents.AspNetCore.HttpRequestExtensions.ToCloudEventAsync(HttpRequest httpRequest, CloudEventFormatter formatter, IEnumerable`1 extensionAttributes)

Repro:
```csharp
var formatter = new JsonEventFormatter<DeploymentScaleEventPayload>();
var cloudEvent = await request.ToCloudEventAsync(formatter);
```

Sample payload to reproduce:
```json
{
   "specversion": "1.0",
   "type": "Kubernetes.Autoscaling.Deployment.V1.ScaleIn",
   "source": "http://kubernetes/core/controllers/deployment",
   "id": "5410aed4-a1a8-48a4-aab4-0417551cbbf9",
   "time": "2021-04-16T06:42:54.7839842Z",
   "subject": "/local-cluster/namespaces/monitoring/deployments/k8s-event-grid-bridge-workload",
   "datacontenttype": "application/json",
   "data": {
      "deployment": {
         "name": "k8s-event-grid-bridge-workload",
         "namespace": "monitoring",
         "labels": {
            "app": "k8s-event-grid-bridge"
         }
      },
      "replicaSet": {
         "name": "k8s-event-grid-bridge-workload-76888d9cc9"
      },
      "replicas": {
         "new": 1
      }
   }
}
```

Although this is so simple that I'm wondering if I'm doing something wrong 😅

**Comment by jskeet** [comment]
What's the content type of the request?

**Comment by jskeet** [comment]
(Admittedly I'm surprised to see that exception from that request anyway. Will look at this when I get a chance.)

**Comment by tomkerkhove** [comment]
Ha you've got me, it's sending in `application/json` but using `application/cloudevents+json; charset=utf-8` works though.

As per the spec:
> Such a representation MUST use the media type application/cloudevents+json.

My bad. Maybe a validation could help here instead of the current exception?

**Comment by jskeet** [comment]
It should still be an ArgumentException, but we could improve the message to indicate "no ce-specversion header found" or similar. I don't know whether that would actually have pointed you towards the error, mind you...

**Comment by tomkerkhove** [comment]
How about this:
> No `ce-specversion` header was found since `application/json` media type is used

**Comment by jskeet** [comment]
That sounds like it would be *perfect* for your particular situation... but seem very odd to someone who was *expecting* a binary mode event, and it just didn't have the ce-specversion header (and maybe it had other CloudEvent headers). I'll ponder on it some more.

**Comment by tomkerkhove** [comment]
Sounds good and happy to contribute once decided!

**Comment by tomkerkhove** [comment]
Thank you @jskeet!
