### ISSUE TITLE
validate cloud event structure

### ISSUE THREAD

**Issue by tanwarsatya** [cloudevents/sdk-csharp#17]
Is there a way to validate cloudevent structure from a json/string. The JsonFormatter is substituting default values for  a message if values are not present. How could we check if a json is valid cloudevent message.

**Comment by jskeet** [comment]
Sorry for not seeing this issue before.

`JsonEventFormatter` now (in the default branch; unreleased) doesn't provide any defaults. You should be able to call `DecodeStructuredModeMessage` passing in a byte array or stream, and it will validate appropriately.

`CloudEvent` itself has a `Validate` method to perform validation and throw an exception if it's invalid, as well as an `IsValid` property that validates without throwing.

Closing as I believe this should be all that's requested, but please add a comment if there's more you were expecting to see.
