### ISSUE TITLE
Enable c# 8.0 Nullable reference

### ISSUE THREAD

**Issue by iron9light** [cloudevents/sdk-csharp#170]
[Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) helps a lot for both develop this lib and use this lib.

This project have already use c# 8.0. It will be great if it enable "Nullable reference" as well.

**Comment by jskeet** [comment]
Thanks for the suggestion - I'll prototype it when I get a chance, and see how it goes.
(I'm not sure whether this would really be called a breaking change or not... hopefully not, given that it should only introduce warnings.)

**Comment by iron9light** [comment]
It should not be a breaking change.
1) It's not changed the API, but helps the users to find potential bugs.
2) Json.Net introduce nullable reference in [12.0.3](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/12.0.3), if the most popular nuget package think it's not a breaking change, we can trust it.

**Comment by jskeet** [comment]
This will be in the 2.1.0 release which is just being published now.
