### ISSUE TITLE
Source should not be of type `Uri`

### ISSUE THREAD

**Issue by VisualBean** [cloudevents/sdk-csharp#180]
The specification technically states "Uri-reference", but the `Uri` type in C# does not allow relative addresses.
ALL examples in the specification, are "/mycontext" which the `Uri` type does not allow for.

**Comment by jskeet** [comment]
It does - so long as you use `UriKind.RelativeOrAbsolute`, which is what the `CloudEventAttributeType.UriReference` uses.

**Comment by VisualBean** [comment]
Thats exactly what I realized 3 seconds after posting this 🙂 sorry - I will make a pull request for the user-guide to not use "new Uri()" in the example but instead use the UriKind overload. How does that sound?

**Comment by jskeet** [comment]
Yup, that sounds great, thanks.
