### ISSUE TITLE
Header ce_time format

### ISSUE THREAD

**Issue by pratikguela** [cloudevents/sdk-csharp#187]
Hi,

Is there anyway of formatting the ce_time.

i.e. if I wanted to format  2021-11-21 00:00:00 to 2021-11-21 00:00:00.000.

Currently the milliseconds are getting removed

**Comment by jskeet** [comment]
Yes, the formatting uses just seconds if the value is a whole number of seconds, then formats to 3, 6 or 7 digits depending on whether it's a whole number of milliseconds, microseconds, or just ticks.

There's no way of affecting this, and I'd rather not add one - what are you using that can't parse the value? (You may well have problems with events created by other SDKs... stopping at seconds is entirely valid.)

**Comment by jskeet** [comment]
Closing as it's working-as-intended, with no more information provided. Please add another comment if you think we should reopen this issue.
