### ISSUE TITLE
Add support/sample for ASP.NET Core

### ISSUE THREAD

**Issue by meteatamel** [cloudevents/sdk-csharp#20]
As far as I can tell, the package does not support ASP.NET Core. Either add support for ASP.NET Core or add a sample showing how to parse for CloudEvents on the server side with ASP.NET Core

**Comment by tanwarsatya** [comment]
It's easy to parse any string message to CloudEvent. Check the unit test project for other examples.

```
 var objjson = (JObject)JToken.Parse(message);

   // create cloud event object
   CloudEvent obj = new JsonEventFormatter().DecodeJObject(objjson);
```

**Comment by meteatamel** [comment]
Thanks for pointing this out. I can parse CloudEvents now. I'll close the issue.
