### ISSUE TITLE
Support cloudEvent.ToKafkaMessage<TKey, TValue>();

### ISSUE THREAD

**Issue by shengLin-alex** [cloudevents/sdk-csharp#203]
We are using this package for building our micro service, and facing some problem.
At first, our JdbcSinkConnector use ByteArrayConverter, and Sink process failed, because no schema found, then we try using JsonSerializer with ISchemaRegistryClient, and find out that KafkaExtensions only support to <string, byte[]> message, make JsonSerializer approach hard to implement.

Will future versions support type parameters or if we can submit a pull request? Thank you very much!

**Comment by jskeet** [comment]
I know almost nothing about Kafka, so I'm not in a good position to implement this. A pull request would be welcome.

**Comment by shengLin-alex** [comment]
Thanks for your reply!
