### ISSUE TITLE
JsonEventFormatter throws exception when charset is included

### ISSUE THREAD

**Issue by cecilphillip** [cloudevents/sdk-csharp#216]
In my AspNetCore app, calling `HttpContext.Request.ToCloudEventAsync(new JsonEventFormatter())` fails when the `datacontenttype` property includes the charset. It throws the following exception => 

```
CloudEvents with a non-JSON datacontenttype can only have string data values.
```

The following is a sample request that was generated by [Dapr](https://dapr.io/).

```
{
  "id": "126e4073-152e-4abe-b638-d1c2c7a79348",
  "specversion": "1.0",
  "topic": "fulfill.order",
  "pubsubname": "rabbitmqbus",
  "datacontenttype": "application/json; charset=utf-8",
  "source": "website",
  "type": "com.dapr.event.sent",
  "data": {
    "stuff": "value"
  }
}
```

When the charset is removed, the code works fine.

**UPDATE**
Just digging around the source seems to be coming from [here](https://github.com/cloudevents/sdk-csharp/blob/ee9d91a398ec880210fc1459a6a0dfa780424e72/src/CloudNative.CloudEvents.SystemTextJson/JsonEventFormatter.cs#L380). 

I don't know what the spec says about including charsets. Otherwise, maybe we can use this check instead
```csharp
ContentType dataContentType = new ContentType(cloudEvent.DataContentType);
if (IsJsonMediaType(dataContentType.MediaType))
```

**Comment by jskeet** [comment]
Thanks, I'll have a look tomorrow.

**Comment by jskeet** [comment]
Yes, it looks like the check you've suggested is the right one - that's what we do everywhere else.
