### ISSUE TITLE
AvroEventFormatter in incorrect namespace

### ISSUE THREAD

**Issue by squanbeck** [cloudevents/sdk-csharp#219]
AvroEventFormatter is currently found in the CloudNative.CloudEvents namespace.

https://github.com/cloudevents/sdk-csharp/blob/3ce4aa08f2763cfd68d5e1a0865ac9442e5b8021/src/CloudNative.CloudEvents.Avro/AvroEventFormatter.cs#L12-L16
To keep things consistent, as with both protobuf and json (first two other examples I looked at), the AvroEventFormatter should be found in CloudNative.CloudEvents.Avro namespace.

Reference to SystemTextJson and Protobuf EventFormatters below.
https://github.com/cloudevents/sdk-csharp/blob/3ce4aa08f2763cfd68d5e1a0865ac9442e5b8021/src/CloudNative.CloudEvents.Protobuf/ProtobufEventFormatter.cs#L18-L22
https://github.com/cloudevents/sdk-csharp/blob/3ce4aa08f2763cfd68d5e1a0865ac9442e5b8021/src/CloudNative.CloudEvents.SystemTextJson/JsonEventFormatter.cs#L12-L16

**Comment by jskeet** [comment]
Humbug. Yes, that absolutely should be in the `CloudNative.CloudEvents.Avro` namespace.

Unfortunately we can't remove it now without taking a new major version (at least for that package).

I suggest I make the existing formatter obsolete (but keep it as-is), and create a new copy in the right namespace. The old one won't get any new features etc.

Does that sound appropriate to you?

(I'll double check the rest at the same time...)

**Comment by squanbeck** [comment]
I was wondering if that might be the case. As far as I am concerned, that sounds perfectly appropriate. At this point, I was just beginning to look into CloudEvents, and so I don't have any current code that depends on this. I only found it due to some first looks at serializing/deserializing CloudEvents using the provided formatters. Thanks for the quick response!
