### ISSUE TITLE
Provide a way to ignore attributes in JSON when decoding/deserialising an event

### ISSUE THREAD

**Issue by andyfurniss4** [cloudevents/sdk-csharp#230]
I am experimenting with CloudEvents and have decided to persist my events to Azure Cosmos. I had a few issues with serialisation but eventually came up with something like this which successfully writes to Cosmos.

```
public override async Task<CloudEvent> AddAsync(CloudEvent item, CancellationToken cancellationToken = default)
{
	var container = CosmosContainerFactory.GetContainer(ContainerName);

	try
	{
		var formatter = new JsonEventFormatter();
		var bytes = formatter.EncodeStructuredModeMessage(item, out _);

		await using var stream = BinaryData.FromBytes(bytes).ToStream();
		var response = await container.CreateItemStreamAsync(
			stream,
			GetPartitionKey(item),
			cancellationToken: cancellationToken
		);

		response.EnsureSuccessStatusCode();
		return item;
	}
	catch (CosmosException ex) when (ex.StatusCode == HttpStatusCode.Conflict)
	{
		throw new CosmosItemAlreadyExistsException(IdProvider.GetId(item));
	}
}
```

I am using the `SystemTextJson` JSON formatter here to encode the message. It feels a bit janky but this seemed to be the only way to simply serialise the event without using any of the `ToHttpContent` stuff (which I don't want/need). Firstly, is there any better way of doing this?

Next, my main issue is that when retrieving an event from my Cosmos table, the deserialisation fails due to the Cosmos system properties containing underscores (which I can see that the CloudEvent spec and validation prohibits). I can see from looking at the `JsonEventFormatter` code that these properties are being treated as event attributes. I want to be able to ignor ethese properties but there doesn't seem to be any way of doing this because:

1) `CloudEvent` is a sealed class so I can't do any fancy inheritance and `[JsonIgnore]` combination.
2) The event formatter does not expose any way of ignoring properties. It just treats any property which isn't a 'standard' property as a custom event attribute.

FWIW, here is my code for fetching an event from Cosmos:

```
public override async Task<CloudEvent?> GetByIdAsync(
	string id,
	PartitionKey partitionKey,
	CancellationToken cancellationToken = default)
{
	var container = CosmosContainerFactory.GetContainer(ContainerName);
	
	try
	{
		var response = await container.ReadItemStreamAsync(
			id,
			partitionKey,
			cancellationToken: cancellationToken
		);
		
		var formatter = new JsonEventFormatter();
		var cloudEvent = await formatter.DecodeStructuredModeMessageAsync(response.Content, new ContentType("application/json"), null);
		return cloudEvent;
	}
	catch (CosmosException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
	{
		return null;
	}
}
```

**Comment by jskeet** [comment]
The serialization part is just a single `formatter.EncodeStructuredModeMessage` - could you clarify what you mean by "a bit janky"? If it's that the result is a `ReadOnlySpan<byte>` and you need to read it as a stream, that's a bit of a side issue.

As for the main issue - it sounds like your JSON is a mixture of "the genuine CloudEvent structured JSON format" and "some other stuff". That sounds like a bad thing in general which could cause no end of problems - you happen to be experiencing one around underscores, but you could equally have other problems.

Can you add a comment with what JSON you receive when reading the data? What's adding the additional system properties, and can you either stop it from doing that, or put the genuine CloudEvent JSON into a sub-property somehow? Fundamentally, if you can't get Cosmos to store *the exact data you're serializing* then that sounds like a big problem.

**Comment by andyfurniss4** [comment]
Hi @jskeet , thanks for getting back to me so soon.

With regards to the first part, it was indeed just related to reading as a stream so as you say, this is mostly just a side issue which I thought I'd add just for a bit of extra feedback!

So, what I am writing is a pure CloudEvent, it's an instance of the class from the the library here. The problem is that Cosmos auto-generates a few properties and stores them along with your original JSON. It seems that the Cosmos SDK does this automatically and doesn't provide any way to control them. You can see the properties documented here: https://docs.microsoft.com/en-us/azure/cosmos-db/account-databases-containers-items#properties-of-an-azure-cosmos-db-container. It's the four which start with an underscore (_rid, _etag, _ts, _self). There's also an _attachments property which doesn't seem to be documented there.

What this results in is the following JSON stored in Cosmos:

```
{
    "specversion": "1.0",
    "id": "4a5d99d6-1c75-4e53-91b9-ee80057d4ce3",
    "subject": "ConsumerAddressModule_20150407.1",
    "type": "com.azuredevops.build.complete.succeeded",
    "source": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/71777fbc-1cf2-4bd1-9540-128c1c71f766/_apis/build/Builds/2",
    "time": "2015-04-07T18:06:10.690Z",
    "datacontenttype": "application/json",
    "data": {
        "id": "4a5d99d6-1c75-4e53-91b9-ee80057d4ce3",
        "eventType": "build.complete",
        "publisherId": "tfs",
        "scope": "all",
        "message": {
            "text": "Build ConsumerAddressModule_20150407.2 succeeded",
            "html": "Build <a href=\"https://dev.azure.com/fabrikam-fiber-inc/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3\">ConsumerAddressModule_20150407.2</a> succeeded",
            "markdown": "Build [ConsumerAddressModule_20150407.2](https://dev.azure.com/fabrikam-fiber-inc/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3) succeeded"
        },
        "detailedMessage": {
            "text": "Build ConsumerAddressModule_20150407.2 succeeded",
            "html": "Build <a href=\"https://dev.azure.com/fabrikam-fiber-inc/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3\">ConsumerAddressModule_20150407.2</a> succeeded",
            "markdown": "Build [ConsumerAddressModule_20150407.2](https://dev.azure.com/fabrikam-fiber-inc/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3) succeeded"
        },
        "resource": {
            "uri": "vstfs:///Build/Build/2",
            "id": 2,
            "buildNumber": "ConsumerAddressModule_20150407.1",
            "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/71777fbc-1cf2-4bd1-9540-128c1c71f766/_apis/build/Builds/2",
            "startTime": "2015-04-07T18:04:06.83Z",
            "finishTime": "2015-04-07T18:06:10.69Z",
            "reason": "manual",
            "status": "succeeded",
            "dropLocation": "#/3/drop",
            "drop": {
                "location": "#/3/drop",
                "type": "container",
                "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/resources/Containers/3/drop",
                "downloadUrl": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/resources/Containers/3/drop?api-version=1.0&$format=zip&downloadFileName=ConsumerAddressModule_20150407.1_drop"
            },
            "log": {
                "type": "container",
                "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/resources/Containers/3/logs",
                "downloadUrl": "https://dev.azure.com/fabrikam-fiber-inc/_apis/resources/Containers/3/logs?api-version=1.0&$format=zip&downloadFileName=ConsumerAddressModule_20150407.1_logs"
            },
            "sourceGetVersion": "LG:refs/heads/master:600c52d2d5b655caa111abfd863e5a9bd304bb0e",
            "lastChangedBy": {
                "id": "d6245f20-2af8-44f4-9451-8107cb2767db",
                "displayName": "Normal Paulk",
                "uniqueName": "fabrikamfiber16@hotmail.com",
                "url": "https://dev.azure.com/fabrikam-fiber-inc/_apis/Identities/d6245f20-2af8-44f4-9451-8107cb2767db",
                "imageUrl": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_api/_common/identityImage?id=d6245f20-2af8-44f4-9451-8107cb2767db"
            },
            "retainIndefinitely": false,
            "hasDiagnostics": true,
            "definition": {
                "batchSize": 1,
                "triggerType": "none",
                "definitionType": "xaml",
                "id": 2,
                "name": "ConsumerAddressModule",
                "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/71777fbc-1cf2-4bd1-9540-128c1c71f766/_apis/build/Definitions/2"
            },
            "queue": {
                "queueType": "buildController",
                "id": 4,
                "name": "Hosted Build Controller",
                "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/build/Queues/4"
            },
            "requests": [
                {
                    "id": 1,
                    "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/71777fbc-1cf2-4bd1-9540-128c1c71f766/_apis/build/Requests/1",
                    "requestedFor": {
                        "id": "d6245f20-2af8-44f4-9451-8107cb2767db",
                        "displayName": "Normal Paulk",
                        "uniqueName": "fabrikamfiber16@hotmail.com",
                        "url": "https://dev.azure.com/fabrikam-fiber-inc/_apis/Identities/d6245f20-2af8-44f4-9451-8107cb2767db",
                        "imageUrl": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_api/_common/identityImage?id=d6245f20-2af8-44f4-9451-8107cb2767db"
                    }
                }
            ]
        },
        "resourceVersion": "1.0",
        "resourceContainers": {
            "collection": {
                "id": "c12d0eb8-e382-443b-9f9c-c52cba5014c2"
            },
            "account": {
                "id": "f844ec47-a9db-4511-8281-8b63f4eaf94e"
            },
            "project": {
                "id": "be9b3917-87e6-42a4-a549-2bc06a7a878f"
            }
        },
        "createdDate": "2016-09-19T13:03:26.4285528Z"
    },
    "_rid": "scdiAP3U4iMEAAAAAAAAAA==",
    "_self": "dbs/scdiAA==/colls/scdiAP3U4iM=/docs/scdiAP3U4iMEAAAAAAAAAA==/",
    "_etag": "\"02005cc2-0000-1000-0000-62fbb0820000\"",
    "_attachments": "attachments/",
    "_ts": 1660661890
}
```

Note the system properties at the bottom.

Normally, when using Cosmos this is not an issue because these are just ignored by the JSON serialiser that the Cosmos SDK uses. But to be able to deserialise a `CloudEvent` I have to use the `JsonEventFormatter` class provided by `CloudNative.CloudEvents.SystemTextJson` and pass the stream from the Cosmos `ReadItemStreamAsync` method (rather than using the method which just does the deserialisation for you - `ReadItemAsync<T>`). The problem here is that `JsonEventFormatter` is treating these as custom event attributes. 

I understand that this is an issue mostly caused by Cosmos but I wondered if we could have a bit of flexibilty in the CloudEvents API to handle situations like this.

Side question: is there a different place you'd recommend persisting CloudEvents?

**Comment by jskeet** [comment]
> I understand that this is an issue mostly caused by Cosmos but I wondered if we could have a bit of flexibilty in the CloudEvents API to handle situations like this.

I really don't think so. The JSON you've provided simply *isn't* a valid structured mode JSON format CloudEvent. It violates the specification, so I think it's absolutely correct for it to fail to parse. As soon as we start accepting bad data, it's a slippery slope - next it'll be "please just lower-case the property names" or "don't worry about JSON that isn't actually valid". I'm a big fan of parsing in a really strict manner, to avoid broken data being presented incompatibly to other code.

If you can't stop Cosmos from modifying the data you're storing, I'd strongly recommend creating a wrapper object instead - put the CloudEvent JSON into a `cloudEvent` property or similar, then when you fetch the stream, parse it and extract that property. We could potentially add public methods to deserialize a `JsonElement`, to avoid having to serialize back and forth a lot. (We've got code like that in the `ProtobufEventFormatter`, for example - `ConvertToProto` and `ConvertFromProto`. Similar methods for JSON formatters could be fine.)

An alternative is to parse the JSON and strip out the extra properties yourself before deserializing. But that sounds a bit risky to me - what's to stop Cosmos from (at some point in the future) modifying your JSON to override the `id` property, for example?

> Side question: is there a different place you'd recommend persisting CloudEvents?

Anywhere that doesn't modify your data silently? ;) Seriously, without knowing what you're trying to achieve, it's very hard to suggest anywhere else.

**Comment by jskeet** [comment]
(If you like the idea of APIs to parse/format to `JsonElement` directly, let me know and I'll start work on a feature PR for that.)

**Comment by andyfurniss4** [comment]
OK, that's fair enough. I totally understand and agree with keeping it strict - that's the whole point of it after all! Just wasn't sure if this was something that had been encountered before and addressed or if it could be addressed elegantly.

For a bit of context, we're trying to build a DORA metrics system so the first step is gathering the events from the various systems we use which is what I'm working on currently.

Wrapping the CloudEvent sounds like a decent suggestion but also having those APIs to parse/format to `JsonElement` would be awesome!

**Comment by jskeet** [comment]
> Wrapping the CloudEvent sounds like a decent suggestion but also having those APIs to parse/format to JsonElement would be awesome!

The latter would make it easier to do that wrapping, of course :)

Tomorrow, I'll close this issue but file a new one as a feature request for those additional methods. (I can see this being a pattern to apply to the XML format as well...)

**Comment by andyfurniss4** [comment]
Fantastic. Thanks a lot Jon!
