### ISSUE TITLE
Binary vs structured

### ISSUE THREAD

**Issue by cfauchere** [cloudevents/sdk-csharp#238]
Hello!
The spec calls out both binary and structured mode [should be supported](https://github.com/cloudevents/spec/blob/3cffde5f0cfadea24dea156e9b65a17df41bc2c2/cloudevents/bindings/http-protocol-binding.md#13-content-modes). I did not see a C# sample using binary. Related to this question: how does the service or the application determines which mode is being used? If I follow the implementation from the sample CloudEvent is expected in the body. Does that mean I need two different endpoints: one for structured and one for binary?

**Comment by jskeet** [comment]
The C# SDK supports binary mode and structured mode almost everywhere that's possible - certainly for HTTP. (There's one binding where we need to do a bit of work, but it's not HTTP.) We simply don't have samples for everything that's available, by a long chalk.

I suggest you look at the code in https://github.com/cloudevents/sdk-csharp/tree/main/src/CloudNative.CloudEvents.AspNetCore and https://github.com/cloudevents/sdk-csharp/tree/main/src/CloudNative.CloudEvents/Http for what you need.

You should be able to use a single endpoint for both structured and binary mode. The sample happens to work by implementing a `TextInputFormatter` which I suspect wouldn't work for binary mode, but if you're happy to just work with the raw request, the extension methods on `HttpRequest` should be fine.

I'll close this issue now as I believe this should cover everything. Please add another comment if you run into problems. (And if you'd like to contribute a sample, that would be great...)
