### ISSUE TITLE
Question about `specVersion` and `CloudEventSpecVersion` type

### ISSUE THREAD

**Issue by jnick422** [cloudevents/sdk-csharp#254]
My team is using a transactional outbox pattern to push `CloudEvent` to AWS SNS and I am wondering if we are serializing the JSON representation of it incorrectly or if the payload is intended to have the entire custom type as opposed to just a `specVersion` property represented as a string. We are serializing the `CloudEvent` with the following code:
```
public OutboxMessage CreateSnsMessage<TPayload>(
            TPayload payload,
            string destinationTopic,
            params ExchangeAttribute[] attributes) where TPayload : CloudEventPayloadBase
        {
            var cloudEvent = new CloudEvent(CloudEventsSpecVersion.V1_0)
            {
                Id = Guid.NewGuid().ToString("N", CultureInfo.InvariantCulture),
                Type = payload.CloudEventType,
                Source = new Uri(payload.CloudEventSource, UriKind.RelativeOrAbsolute),
                Time = DateTimeOffset.UtcNow,
                DataSchema = new Uri(payload.DataSchema, UriKind.RelativeOrAbsolute),
                DataContentType = MediaTypeNames.Application.Json,
                Data = payload
            };

            var cloudEventJson = JsonConvert.SerializeObject(cloudEvent);
            var validationSettings = new JsonSchemaValidatorSettings
            {
                PropertyStringComparer = StringComparer.OrdinalIgnoreCase
            };
            var schema = NJsonSchema.JsonSchema.FromType<CloudEvent>();
            var validationErrors = schema.Validate(cloudEventJson, validationSettings);
            if (validationErrors.Any())
            {
                throw new JsonSchemaException($"Invalid JSON for cloud event: {string.Join(", ", validationErrors)}");
            }

            return OutboxMessage.CreateTopicMessage(destinationTopic, cloudEventJson, attributes);
        }
```
The `cloudEventJson` is saved by itself as a string to the database, while we have all other meta data, such as the `attributes` as key-value pairings, isolated away from the message.
When looking at the JSON string visualizer using Visual Studio, instead of `specVersion` being represented as a string, it seems to be represented as a custom type:
![image](https://user-images.githubusercontent.com/49107757/220734153-9a34fc48-9e6d-4b1b-9822-0dc24098744d.png)

These are the examples I'm looking at for what a message might look like: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md#23-examples

I am guessing there is a chance we are serializing the message incorrectly, but the formatters in the docs seem to be used for serializing streams to byte representations of HttpContent as opposed to just creating stringified json, so we weren't sure what we need to do.

**Comment by jskeet** [comment]
I'm not in a position to leave a long comment now, but this line is the problem:

```csharp
var cloudEventJson = JsonConvert.SerializeObject(cloudEvent);
```

`CloudEvent` objects aren't intended to be serialized using `JsonConvert` or the equivalent. Instead, use a `CloudEventFormatter`, such as `JsonCloudEventFormatter` (in either CloudNative.CloudEvents.NewtonsoftJson or CloudNative.CloudEvents.SystemTextJson). Currently I don't think (off the top of my head) that there's a simple way to convert it to a JSON *string* (as event formatters are designed for serializing to binary data) - but you could call `new JsonEventFormatter().ConvertToJObject(cloudEvent).ToString()` as one shortcut, for example. (I can look at adding a `ConvertToJsonString` or similar method another time...)

**Comment by jnick422** [comment]
Thanks for the quick reply, I can try leveraging the formatters and will post results.

**Comment by jnick422** [comment]
The suggested fix does populate the `specVersion` with the expected value. 
![image](https://user-images.githubusercontent.com/49107757/220751959-88a4be19-86bc-469f-a4b1-29dd934d0272.png)
Thanks for the help :)

**Comment by jskeet** [comment]
Hooray, that's great to hear. I'll file a feature request issue for "this should be simpler" though :)
