### ISSUE TITLE
Unexpected auto-generated class name from CloudNative.CloudEvents.Protobuf 

### ISSUE THREAD

**Issue by gbrulotte** [cloudevents/sdk-csharp#256]
Hi, we have a use case where we want to generate a CloudEvent in a service using CloudNative.CloudEvents and send it in the protobuf format using CloudNative.CloudEvents.Protobuf in a gRPC call. We defined a custom .proto containing the service and wanted to re-use the existing CloudEvent proto (https://github.com/cloudevents/spec/blob/main/cloudevents/formats/cloudevents.proto) within our service proto to be able to deserialize the event on the server side in a CloudNative.CloudEvents CloudEvent.

Since the CloudNative nuget package already bundles the auto-generated classes, we need to reference the CloudEvent proto without compiling it. With this configuration, I get this error:

`error CS0234: The type or namespace name 'CloudeventsReflection' does not exist in the namespace 'CloudNative.CloudEvents.V1' (are you missing an assembly reference?)
`

From what I see in https://github.com/cloudevents/sdk-csharp/blob/main/generate_protos.sh, the cloudevents.proto is copied in a file named ProtoSchema.proto. This results in an auto-generated class named ProtoSchemaReflection (https://github.com/cloudevents/sdk-csharp/blob/main/src/CloudNative.CloudEvents.Protobuf/ProtoSchema.g.cs#L15) instead of being named CloudeventsReflection.

Would it be possible to instead keep the original proto file name (cloudevents.proto) to keep compatibility?

Here is a sample showing the problem: https://github.com/gbrulotte/CloudEventProtobufSample.

Thanks!

**Comment by jskeet** [comment]
Unfortunately changing that now would be a breaking change for anyone who already refers to ProtoSchemaReflection. I suspect there was some problem with keeping the original name - I don't know why else I'd have changed it, to be honest.

I'll have a closer look on Monday.

**Comment by jskeet** [comment]
Will try to look fully later on today, but one option I'll look into is renaming, but adding a handwritten ProtoSchemaReflection class which just delegates to CloudEventReflection, for compatibility.

**Comment by jskeet** [comment]
Will do a release tomorrow.

**Comment by jskeet** [comment]
Release 2.6.0 is now available - do let me know if you still have issues. (I've tried your sample project, and that now builds, so hopefully that was all that was needed.)
