### ISSUE TITLE
Knative Functions support?

### ISSUE THREAD

**Issue by giuliohome** [cloudevents/sdk-csharp#259]
Any plan to support [Knative Functions](https://knative.dev/docs/functions/) in C#? 

I see other languages base their[ language packs](https://github.com/knative/func/blob/main/docs/language-packs/language-pack-contract.md#built-in-language-packs) on CloudEvents.

**Comment by jskeet** [comment]
I wouldn't expect anything specific to be in *this* repo - instead, I'd expect any language pack to use the libraries published from this repo to consume CloudEvents.

It's entirely possible that you could use the [.NET Functions Framework](https://github.com/GoogleCloudPlatform/functions-framework-dotnet) as the basis of a language pack. I'm afraid that's not something I'd personally have time to look into though.

**Comment by giuliohome** [comment]
Yes, I've had the feeling that it was more advanced for Google Cloud Platform than let's say for Azure or specifically for AKS (e.g. I noticed that this [repo for azure functions](https://github.com/triggermesh/azure-runtime) is archived, it sounds strange to me...).

Ok, thank you for the super fast answer 👍
