### ISSUE TITLE
Optional custom serializer for AvroEventFormatter 

### ISSUE THREAD

**Issue by Kirner-** [cloudevents/sdk-csharp#261]
It would be useful for those using Confluent Kafka tools to have the option to supply a custom serializer.

The Confluent tools expect serializers and de-serializers to use [this wire format ](https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#wire-format)(adding additional schema information to the message). As a result, tools such as [Kafka-UI ](https://github.com/provectus/kafka-ui)fail to de-serialize messages encoded using the `AvroEventFormatter`, even when supplied with the correct schema.

If we could supply the formatter with a custom serializer, then those using Confluent or similar tools could make use of their built-in serializers whilst still relying on the CloudEvents SDK to handle the `GenericRecord` formatting. 

Something along the lines of:

```c#
public interface IGenericRecordSerializer
{
    ReadOnlyMemory<byte> Serialize(GenericRecord value);
    ReadOnlyMemory<GenericRecord> Deserialize(Stream value);
}

```
That can be passed to the formatter like so:
```c#
var formatter = new AvroEventFormatter(new MyCustomerSerializer());
var kafkaMessage = myCloudEvent.ToKafkaMessage(ContentMode.Structured, formatter);
```

I'd happily work on these changes if desired.

**Comment by jskeet** [comment]
I know basically nothing about Kafka, but if you're happy to work on this and come up with something which doesn't break compatibility, I'm very happy to review it :)

**Comment by Kirner-** [comment]
That's great, thanks for the quick reply.
I'll make a PR over the weekend :D

**Comment by jskeet** [comment]
This is now released - please shout if you find any problems.
