### ISSUE TITLE
Only include System.Memory for Net Standard 2.0

### ISSUE THREAD

**Issue by thompson-tomo** [cloudevents/sdk-csharp#278]
### Summary
I want System.Memory to only be a dependency when not provided by the application framework

### Proposal
Make System.Memory added conditionally so that it is only included for Net Standard 2.0

**Comment by jskeet** [comment]
Yup, that sounds reasonable (although I have vague memories of trying it when we added another framework, and failing; I'm hoping I'm just misremembering.)

**Comment by thompson-tomo** [comment]
@jskeet i am more than happy to take a look at given i have done this on other projects

**Comment by jskeet** [comment]
PRs definitely welcome :) I'm on vacation at the moment though, so may take a little while to review.

**Comment by thompson-tomo** [comment]
No problem at all & I am in no rush. Pr is done as  #279 and note I found 2 other packages I could tweak the conditions on to reduce dependencies, so I did them at the same time.
