### ISSUE TITLE
Work out how to remove netstandard2.1 target

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#280]
As noted in #279, we don't really need a netstandard2.1 build... but when targeting .NET 6 (and presumably 7, or even .NET Core App 3.1) we end up with a problem if we refer to the netstandard2.0 build. We use the `Nullable` package like this:

```xml
  <ItemGroup>
    <!-- Source-only package with nullable reference annotations. -->
    <PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="All" />
  </ItemGroup>
```

That causes problems in our .NET 6.0 test target, where we use `[DisallowNull]`:

> error CS0433: The type 'DisallowNullAttribute' exists in both 'CloudNative.CloudEvents, Version=2.7.1.0, Culture=neutral, Publi
cKeyToken=eb8e1fd825734e88' and 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

With our current netstandard2.1 build in place, it's fine, because the `Nullable` package is a no-op for any platform that already supports the annotations.

I can't immediately think of any situations where this will *currently* cause a problem, but it may prevent us from removing the netstandard2.1 target.

@captainsafia have you run into situations like this? (It feels like it's probably a common enough problem...)

**Comment by captainsafia** [comment]
> @captainsafia have you run into situations like this? (It feels like it's probably a common enough problem...)

We use a similar approach to the `Nullable` package reference in ASP.NET Core with our own bespoke [NullableAttributes.cs](https://github.com/dotnet/aspnetcore/blob/9742e7d7d0d9535c73292f7d827e7b931e733ff2/src/Shared/Nullable/NullableAttributes.cs) and configure some MSBuild to include these source files in any projects that are compiled with nullability-enabled ([ref](https://github.com/dotnet/aspnetcore/blob/9742e7d7d0d9535c73292f7d827e7b931e733ff2/eng/targets/CSharp.Common.targets#L111-L132)).

You'll note from our MSBuild that we use a `SuppressNullableAttributesImport` property to suppress inclusion of the types from projects where they might already be visible from a project reference that had an IVT attribute set (which is the case with our test dependencies).

We could consider setting up similar targets here?

**Comment by captainsafia** [comment]
>  To be honest, I don't quite follow the suggestion, but I'd be happy to see a PR for it - or we could decide that keeping a netstandard2.1 target is just a simple way to work round the issue.

I spent some time trying to get this working but as it turns out there's some custom logic in the build for the dotnet/aspnetcore repo that doesn't immediately translate here.

With that set, I'm fine retaining the `netstandard2.1` targets to save us the headache.
