### ISSUE TITLE
Move to a framework reference

### ISSUE THREAD

**Issue by thompson-tomo** [cloudevents/sdk-csharp#286]
The CloudNative.CloudEvents.AspNetCore package currently has a dependency on the Microsoft.AspNetCore.Http nuget package which was deprecated as part of the dotnet clean up https://github.com/dotnet/announcements/issues/217.

As such we should move to using a framework reference to eliminate this dependency especially as the name clearly indicates it is for aspnet.

**Comment by jskeet** [comment]
Hmm... that makes perfect sense for applications; I'm not sure what impact it would have for *libraries* or compatibility.

@captainsafia is this something you know more about?

**Comment by thompson-tomo** [comment]
@jskeet here is an ai bot also suggesting to make this change for another project and i have made the change in a number of other libraries i use. ;) https://github.com/elsa-workflows/elsa-core/issues/5107#issuecomment-2010675592

**Comment by captainsafia** [comment]
Yes, the typical pattern for managing these references is to use the `FrameworkReference` for things targeting `netcoreapp3.0` and above and individual package references for `netstandard2.0` targets.

The [official docs on this](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore) go into more detail.

**Comment by thompson-tomo** [comment]
@jskeetThere is a pr for u.

**Comment by jskeet** [comment]
@thompson-tomo: Yes, I get notified of new PRs automatically, but it was 10pm on a Friday. I'll get to it when I'm back working next week.
