### ISSUE TITLE
Receiving a cloudevent in binary mode is parsed incorrectly

### ISSUE THREAD

**Issue by stockmansy** [cloudevents/sdk-csharp#293]
Hi,

Recently I've been trying to receive cloudevents. Cloudevents posted in the structured mode work as expected but cloudevents posted in the binary mode are all parsed in a wrong manner. All properties are null.

![image](https://github.com/cloudevents/sdk-csharp/assets/483904/c79620e4-b816-4bde-92b2-e07c728ccc21)

Request looks like:
POST https://localhost:7005/v1/postEvent
ce-type my.type
ce-time 2024-06-07T12:34:56.789Z
ce-source myservice/mysource
ce-id 9001
ce-specversion 1.0
Content-Type application/json
{
 "some": "data"
}

**Comment by jskeet** [comment]
If you could provide a way of reproducing this with an *actual* request rather than pseudocode (ideally code to make a request, along with the server that's receiving it) that would be helpful. If I can't reproduce the problem, it's going to be hard to diagnose it.

**Comment by stockmansy** [comment]
Fair enough, so I mostly tested it with postman. But here's some code:

Create and send post event snippet:

```var cloudEvent = new CloudEvent
{
    Id = Guid.NewGuid().ToString(),
    DataContentType = MediaTypeNames.Application.Json,
    Data = new { Name = "test" },
    Type = "com.example.myevent",
    Time = DateTimeOffset.Now,
    Source = new Uri("urn:example-com:mysource:abc")
};
var content = cloudEvent.ToHttpContent(ContentMode.Binary, new JsonEventFormatter());

var httpClient = new HttpClient();
var result = await httpClient.PostAsync(new Uri("https://localhost:7085/v1/postEvent"), content);
```

Receive action:
```
using CloudNative.CloudEvents;
...
[HttpPost]
[Route("postEvent")]
public ActionResult PostEvent([FromBody] CloudEvent cloudEvent)
{
...
}

```

Works when using ContentMode.Structured instead of ContentMode.Binary:

![image](https://github.com/cloudevents/sdk-csharp/assets/483904/5df63b20-61dd-401e-8928-3286a5f178b4)

**Comment by jskeet** [comment]
So what code did you add to deserialize the body as a CloudEvent? (Complete code would make it much easier to reproduce...)

**Comment by stockmansy** [comment]
I found the issue the cloudevent formatter was being 'added' and not inserted at index 0.
opts.InputFormatters.Insert(0, cloudEventFormatter); is now working.

Tnx for the replies!
