### ISSUE TITLE
Support cloudevents v1.0

### ISSUE THREAD

**Issue by iron9light** [cloudevents/sdk-csharp#30]
It seems the v1.0 of cloudevents has released days ago.
https://github.com/cloudevents/spec/releases/tag/v1.0
Could you support it?
We are considering using the v1.0 cloudevents as our default message format for our project.

**Comment by tomkerkhove** [comment]
+1

**Comment by clemensv** [comment]
1.0 had already been checked in a few weeks ago, but the doc has not been updated. I'll do that promptly.
