### ISSUE TITLE
CloudEvent Source type

### ISSUE THREAD

**Issue by glucaci** [cloudevents/sdk-csharp#315]
Hi,

I wanted to write a mapping between the [Azure.Messaging.CloudEvent](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Messaging/CloudEvent.cs) which is JSON spec conform and the `CloudNative.CloudEvents.CloudEvent` and realized the difference on the `Source` Property type.

There is any reason why in `CloudNative.CloudEvents.CloudEvent` the `Source` property is `Uri` because in `Azure.Messaging.CloudEvent` it's a `string`. 

Also taking a look of the [spec examples](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#source-1) and taking the value `1-555-123-4567`, can be seen that this is not a valid value for an `Uri` type.

Thanks for clarification!

**Comment by jskeet** [comment]
1-555-123-4567 *is* a valid URI reference. It's unusual for sure, but it's valid.

Here's some sample code showing it in action:

```csharp
using CloudNative.CloudEvents;
using CloudNative.CloudEvents.SystemTextJson;
using System.Text;

var evt = new CloudEvent
{
    Id = "my-id",
    Source = new Uri("1-555-123-4567", UriKind.RelativeOrAbsolute),
    Type = "my-type"
};

evt.Validate();
CloudEventFormatter formatter = new JsonEventFormatter();
var bytes = formatter.EncodeStructuredModeMessage(evt, out _);
var json = Encoding.UTF8.GetString(bytes.Span);
Console.WriteLine(json);
```

Output: 

```json
{"specversion":"1.0","id":"my-id","source":"1-555-123-4567","type":"my-type"}
```

Fundamentally, the `Source` property is a `Uri` because the type of the `source` attribute (see the spec examples link you had before) is `URI-reference`.

**Comment by glucaci** [comment]
Thanks for the clarification, but then why Microsoft decided to use a `string` type on the `Source` property is a good question.

**Comment by jskeet** [comment]
I can't answer that, I'm afraid. I'm going to close this issue now as I believe I've answered it as thoroughly as I can.
