### ISSUE TITLE
Feature Request: Protobuf formatter support

### ISSUE THREAD

**Issue by thangchung** [cloudevents/sdk-csharp#35]
I have seen that we have [JsonEventFormatter](https://github.com/cloudevents/sdk-csharp/blob/master/src/CloudNative.CloudEvents/JsonEventFormatter.cs), and that would be great if we can support **ProtobufFormatter** too because of **gRPC template** on .NET Core 3.0, then some of usecases which are using **Protobuf format** such as message with Protobuf and put to Kafka or transfer gRPC services back and forth with Protobuf message...

**Comment by clemensv** [comment]
There is no official Protobuf binding for CloudEvents as of yet, so there's nothing to bind to. Please open an issue in the "spec"repo, @thangchung
