### ISSUE TITLE
HttpSend Project will fail on Authentication

### ISSUE THREAD

**Issue by codeputer** [cloudevents/sdk-csharp#36]
I was not able to get it to work as it is, as the httpClient does not have the aeg-sas-key.. I added it this way and started to get OK's from the HTTP requests

      _HttpClient.DefaultRequestHeaders.Add("aeg-sas-key", new List<string>() { pAccessKey });

HttpSend project, Program.cs, line 40 & 41
            var httpClient = new HttpClient();
            var result = (await httpClient.PostAsync(this.Url, content));

(Also never seen a Program.cs with Option attributes before - might be worth a comment or two as to why this is created this way.

**Comment by clemensv** [comment]
The HTTP client mapping only maps the CloudEvent. Your app remains responsible for adding any headers that are required for the particular HTTP endpoint you are targeting. This is not the Event Grid SDK, but a generic SDK for any HTTP endpoint. I'll look at where extra comments will help.
