### ISSUE TITLE
Serialize json using System.Text.Json

### ISSUE THREAD

**Issue by brechtvhb** [cloudevents/sdk-csharp#42]
Are there any plants to use system.text.json as serializer instead of newtonsoft?

If you have an application that uses system.text.json it hurts to add a dependency to newtonsoft.json when using cloud events.

**Comment by tomkerkhove** [comment]
Heh, I would have same scenario after this would be implemented as we're using newtonsoft.

Does it still hurt so much to add another dependency today? 🤷‍♂

**Comment by brechtvhb** [comment]
As System.Text.Json is faster than newtonsoft & built into .net 3.0 it might make sense.
Hey lets all use EDI flatfiles because why would we start using json.

**Comment by tomkerkhove** [comment]
I'm fine with both packages frankly but majority still uses newtonsoft given everything is depending on it, for now.

**Comment by RascoApps** [comment]
it's now the time to change it and support both?

**Comment by jskeet** [comment]
Given that users of either one probably don't want the dependency on the other, it might make sense to split them out into separate packages: CloudNative.CloudEvents.NewtonsoftJson and CloudNative.CloudEvents.SystemTextJson.

**Comment by RascoApps** [comment]
Agreed.

Send from iPhone
________________________________

**Comment by rynowak** [comment]
> Given that users of either one probably don't want the dependency on the other, it might make sense to split them out into separate package

+1 - this was our calculus for not using the CloudEvents package in https://github.com/dapr/dotnet-sdk/ - if we have an option to use this package without JSON.NET as a dependency, we definitely would.

**Comment by jskeet** [comment]
@rynowak: Glad to hear that. I've just merged the change to split them out, but there's still a lot of work to do before 2.0. Once we're at the stage where we've at least got stable betas (and docs!), it would be great to hear more feedback about whether we're going in the right direction in general.
