### ISSUE TITLE
ASP.NET Core example to show how to return a CloudEvent

### ISSUE THREAD

**Issue by meteatamel** [cloudevents/sdk-csharp#43]
The ASP.NET Core example shows how to receive and a CloudEvent. However, there's no example to show how to return a CloudEvent from a controller. I've been trying to figure this out with no success so far. A sample would be quite helpful.

**Comment by jskeet** [comment]
We can do better than an example... we should have an extension method of:

```csharp
public static CopyToHttpResponse(
    this CloudEvent cloudEvent,
    HttpResponse response,
    ContentMode contentMode,
    CloudEventFormatter eventFormatter)
```

... and probably the same for `CopyToHttpRequest` as well. Shouldn't be *terribly* hard to do that, given the other implementations we've got.

**Comment by jskeet** [comment]
This is now covered in #148 as a broader review of HTTP method availability.
