### ISSUE TITLE
Feature suggestion - Batched CloudEvents

### ISSUE THREAD

**Issue by stijnmoreels** [cloudevents/sdk-csharp#44]
**What feature would you like?**
The [CloudEvents spec](https://github.com/cloudevents/spec/blob/master/json-format.md#4-json-batch-format) describes how events could also be batched together and given a specific `Content-Type: application/cloudevents-batch+json`.

The current SDK implementation only allows single events to be parsed.

_Receiving_
It would be nice when the `DecodeJObject` takes into account if the token is an `Object` or an `Array` so we can benifit from this approach.

_Sending_
A new `HttpContent` implementation for batched events could be added for this too. Maybe take in a sequence of cloud events for this.

**Comment by jskeet** [comment]
We should bear this in mind when redesigning event formatters in #55.

**Comment by jskeet** [comment]
(We didn't pay much attention to this when redesigning, as it happens... so we may need to do another round.)

**Comment by jskeet** [comment]
#111 implements the event formatter part. We'll then need protocol binding methods.
