### ISSUE TITLE
Support Custom JSON JsonSerializerSettings

### ISSUE THREAD

**Issue by RascoApps** [cloudevents/sdk-csharp#46]
I would like to customize the serilizer to not send the null properties in the message. I am able to do this by changing the default settings, but I do not want to change this for the entire application and would rather not clone to default settings, do the work and then set back to the original settings.

any more ideas?

I currently have this
`  JsonConvert.DefaultSettings = () => new JsonSerializerSettings
   {
        NullValueHandling = NullValueHandling.Ignore
   };`

**Comment by iron9light** [comment]
Try [CloudNative.CloudEvents.Json](https://github.com/iron9light/CloudNative.CloudEvents).
It's a rewrite of ICloudEventFormatter for JSON.

```csharp
var jsonSerializerSettings = new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.DateTimeOffset,
    DateTimeZoneHandling = DateTimeZoneHandling.Utc,
};
var formatter = new JsonCloudEventFormatter<MyData>(jsonSerializerSettings); // JsonSerializerSettings is optional
var cloudEvent = formatter.DecodeStructuredEvent(jsonData);
cloudEvent.Data.Should().BeOfType<MyData>(); // The type of Data is MyData type, but not JToken
```

**Comment by jskeet** [comment]
This is now implemented in the JsonEventFormatter in this repo, so I'll close this issue.
(It does *not* do the deserializing shown above, although a subclass could.)
