### ISSUE TITLE
Clarify CloudEvent formatter responsibilities

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#55]
I'm writing a doc to help myself think about this more clearly, but it feels to me like there's a lack of clarity around when data should be converted in what exact way.
We may want to change the actual code to make this clearer, or it may just be a matter of fixing docs. We'll see.

One key result I'd like to see: code that says (for example) "Populate HttpRequestMessage from CloudEvent" then "Convert HttpRequestMessage to CloudEvent" should be able to roundtrip in both directions, without gaining extra levels of encoding on each cycle, which I suspect it would do now without care.

**Comment by jskeet** [comment]
My current thinking is along the lines of:

- Event formats are *only* relevant for structured content modes. They shouldn't be required when dealing with binary content modes.
- For binary content modes, it may be reasonable to say that we *require* the `Data` property to be one of a few specific types, e.g. `ReadOnlyMemory<byte>` or `byte[]`, and when decoding we always end up with a `ReadOnlyMemory<byte>` as the `Data` in the resulting property
- For structured content mode, the event formatter is responsible for defining what combination of CLR types for `Data` and `datacontenttype` attributes are valid when encoding, along with working out what data type to use when decoding
- We should strongly discourage any event formatters from creating a `CloudEvent` with a `Data` property value of type `Stream`... it's really fragile in terms of ownership.
- As discussed on a previous call, let's make `CloudEventFormatter` an abstract class instead of an interface.

@JoshLove-msft: If this sounds right to you, I might start work on this next week.

**Comment by jskeet** [comment]
Additionally, we *may* want to remove the `ContentMode` enum - it's not clear that it's particularly useful.

**Comment by jskeet** [comment]
Note: it might be useful to get event formatters involved after all, for consistency when decoding.

**Comment by JoshLove-msft** [comment]
> My current thinking is along the lines of:
> 
> * Event formats are _only_ relevant for structured content modes. They shouldn't be required when dealing with binary content modes.
> * For binary content modes, it may be reasonable to say that we _require_ the `Data` property to be one of a few specific types, e.g. `ReadOnlyMemory<byte>` or `byte[]`, and when decoding we always end up with a `ReadOnlyMemory<byte>` as the `Data` in the resulting property
> * For structured content mode, the event formatter is responsible for defining what combination of CLR types for `Data` and `datacontenttype` attributes are valid when encoding, along with working out what data type to use when decoding
> * We should strongly discourage any event formatters from creating a `CloudEvent` with a `Data` property value of type `Stream`... it's really fragile in terms of ownership.
> * As discussed on a previous call, let's make `CloudEventFormatter` an abstract class instead of an interface.
> 
> @JoshLove-msft: If this sounds right to you, I might start work on this next week.

This all sounds good to me. I'm also interested in how the the JSON event formatter will determine whether the data is considered binary - https://github.com/cloudevents/sdk-csharp/blob/master/src/CloudNative.CloudEvents.NewtonsoftJson/JsonEventFormatter.cs#L135-L149

**Comment by jskeet** [comment]
This is implemented in #97, but I'll leave this issue open until we've written docs.
