### ISSUE TITLE
Determine spec version support

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#56]
Assuming we're creating a 2.0 (as various changes such as strong-naming are breaking changes) we should decide whether we still need to support CloudEvents prior to 1.0. For reference, the dates are:

- 1.0: October 2019
- 0.3: June 2019
- 0.2: December 2018
- 0.1: April 2018

I would hope that by the time the library 2.0 goes GA (which is unlikely to be before December), there'd be no requirement to support spec 0.3 and earlier any more.

**Comment by tomkerkhove** [comment]
Sounds fair to me!

**Comment by jskeet** [comment]
The [SDK spec](https://github.com/cloudevents/spec/blob/master/SDK.md) specifically calls out:

> Each SDK supports the latest(N), and N-1, major releases of the CloudEvent spec*.
> ...
> *Note: v1.0 is a special case and it is recommended that as long as v1.0 is the latest version, SDKs should also support v0.3.

So it's *recommended* but not *required* that we continue to support 0.3. I'm going to have a look at the differences between them now.

**Comment by jskeet** [comment]
As of #92, we only support 1.0+.
