### ISSUE TITLE
Consider changing the type of CloudEvent.Time to DateTimeOffset

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#57]
Two benefits of this:

- It accurately reflects the spec, which talks about a "timestamp" type - a `DateTime` with a `Kind` of `Local` or `Unspecified` does *not* represent a timestamp in general. (A kind of `Local` can be converted to a timestamp, if we assume that assumption of "system default time zone" is actually correct, but it's pretty ugly.)
- It allows the UTC offset described in [RFC3339](https://tools.ietf.org/html/rfc3339) to be preserved

One downside: there's no way of representing "Unqualified Local Time" or "Unknown Local Offset Convention" in `DateTimeOffset`

Personally I believe the benefits outweigh the downside, for values which are really expected to be timestamps, but I'm happy to discuss it.

**Comment by jskeet** [comment]
It's worse than I thought - currently the HTTP parsing ends up returning a DateTime with a kind of *local* which is all kinds of wrong.

**Comment by PSanetra** [comment]
This is quite important. Do you plan to release a version 2.0 of this lib with a fix?

**Comment by jskeet** [comment]
@PSanetra: Yes, definitely. I'm hoping that'll be one of the next changes to land.

We've released (slightly accidentally) a 2.0.0-beta.1 which was mostly get a strongly-named version out, but there are plenty of other changes we want to get done for a v2.0 release.

**Comment by jskeet** [comment]
I'm actively working on this now.
