### ISSUE TITLE
Revisit extensions design

### ISSUE THREAD

**Issue by jstafford5380** [cloudevents/sdk-csharp#74]
I might be ignorant on this, but I haven't found any documentation to clarify regarding extensions. Right now, when you're writing a new event, I figured out how to attach extension properties using some of the extensions that are in this repo, but because of the way the Attach() method is formed, it requires some info up front in the constructor. I can set some private fields in the ctor and then reference them in the attach method. Everything builds and serializes just fine.

Coming the other direction, however... if I use `JsonEventFormatter` as suggested, it requires that I call out any extensions in the Decode method and then it seems to execute those in the exact same way which means I need those ctor arguments upfront but I don't have those because they're in the message. Short of deserizlizing to JToken and digging them out, I'm not sure how this is supposed to work.

Is this a design flaw or am I doing this wrong?

**Comment by jskeet** [comment]
I've just been looking at extensions myself, and they're not particularly clear to me. @JoshLove-msft we should look at this as part of milestone 3, while considering event formatters.

**Comment by jskeet** [comment]
This has been revisited in #92, but I'll leave this open until I've written up some docs about it.
