### ISSUE TITLE
Amqp extensions - bad implementation?

### ISSUE THREAD

**Issue by darthkurak** [cloudevents/sdk-csharp#8]
Hi! 
Im trying to do Azure EventHub extension for CloudEvents. As example i took Amqp extension, and notice a few flaws in current implementation, according to this description:

> The CloudEvent.Data property is object typed, and may hold any valid serializable CLR type. The following types have special handling:
> 
> System.String: In binary content mode, strings are copied into the transport message payload body using UTF-8 encoding.
> System.Byte[]: In binary content mode, byte array content is copied into the message paylaod body without further transformation.
> System.Stream: In binary content mode, stream content is copied into the message paylaod body without further transformation.
> Any other data type is transformed using the given event formatter for the operation or the JSON formatter by default before being added to the transport payload body.
> 
> All extension attributes can reached via the CloudEvent.GetAttributes() method, which returns the internal attribute collection. The internal collection performs all required validations.

AmqpCloudEventMessage.cs
1. formatter - would be nice to have this null as default
2. if formatter is null it is not replaced by default JSON formatter
3. if contentMode different than Structured, and cloudEvent.Data is not met the special handling cases, cloudEvent.Data is not prepared with formatter and attached to BodySection. Simply, BodySection will be empty. 
4. if we try numer 3 fix using formatter.EncodeAttribute(cloudEvent.SpecVersion, CloudEventAttributes.DataAttributeName(cloudEvent.SpecVersion), cloudEvent.Data, cloudEvent.Extensions.?);
- EncodeAttribute ignore all Data attribute which are not a Stream ?!
- the stream one serialize byte[] array into json and then to string - what is the purpose of that? Isn't that volataile > System.Stream: In binary content mode, stream content is copied into the message paylaod body without further transformation. rule?
- cloudEvent.Extensions is not accessed in AmqpExtension project - as it is internal - should we provide for it access? (internalvisibleto?) 

5. `else if (attribute.Value is DateTime || attribute.Value is DateTime || attribute.Value is string)`
a small duplication of `attribute.Value is DateTime `

Most of this can be fixed fairly easy, i can introduce fixes in PR if my understanding of this i correctly - but the most what concern me is the EncodeAttribute method. With current implementation i cannot implement: 

> Any other data type is transformed using the given event formatter for the operation or the JSON formatter by default before being added to the transport payload body. 

as EncodeAttirubte ignore all Data objects which are not a Stream.

**Comment by clemensv** [comment]
1/2: I don't want to make this implicit just yet.
3ff: 

I understand the concern. I am a bit on the fence on what the right solution is for this. 

For binary mode, I would really prefer that the input (contentType plus data) is explicit and pre-encoded, i.e. only allowing string or binary as I do now but don't yet enforce by throwing. 

The event format does NOT cover serializing the payload, so for the event formatter to also turn an object graph in the "data" field into JSON content in passing, were not formally correct. I do understand the usability attraction of that, though. 

I'll think about it.

**Comment by jskeet** [comment]
FWIW, I'm currently struggling with the aspect of what's responsible for performing conversions of the data (payload). It feels like there's a little bit of a lack of separation of concerns in the spec at the moment, but I'm trying to understand it better so I can express my concerns more clearly - that will probably then feed into possible changes in the SDK.

**Comment by jskeet** [comment]
A couple of notes on this now, a lot later:

- The JSON formatter is now in a separate package, so *must* be specified. There's basically no concept of a "default" formatter. This allows us to avoid a dependency on Json.NET (or System.Text.Json) within the core SDK - and personally, I think that being explicit makes things clearer.
- I'm going to revisit what AMQP (and other transports and event formats) do with streams. I suspect that it would be better to not support streams at all as Data members (at least within the transports in this repo). There's so much that can go wrong

One note on a previous comment from @clemensv:

> The event format does NOT cover serializing the payload

Except it sort of does, in the JSON event formatter, as described in [the JSON event formatter section 3](https://github.com/cloudevents/spec/blob/v1.0.1/json-format.md#3-envelope).

If event formatters were firmly delineated to require a blob of data and represent that, there would be a much clearer separation of concerns - but JSON events would be considerably harder to read.

**Comment by jskeet** [comment]
I believe this is now effectively fixed as far as we intend to go. We no longer support streams in any event formatters, and it's up to the event formatter how data is handled. Closing as I don't think there's anything more to do here.
