### ISSUE TITLE
Consider whether we need resources for error messages

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-csharp#83]
Currently exception error messages are in a resource string lookup. This has two advantages and one disadvantage:

- It's localizable
- We can potentially improve consistency, using the same resource in multiple places
- It makes the code throwing the exception more complex

Experience suggests we won't *actually* get round to localizing the exception message... so do we think the remaining advantage is worth the complexity disadvantage?

**Comment by jskeet** [comment]
Assigning to Josh for comment.

**Comment by jskeet** [comment]
Example of where it's slightly unhelpful: one of our resource strings is actually wrong. It uses the attribute name "contenttype" when it should be "datacontenttype", presumably because the name has changed in the spec.

**Comment by JoshLove-msft** [comment]
Looking through the resources file, it does appear that there are several strings that are reused in multiple places. In terms of adding new strings, I think the resources are a bit more cumbersome, but given that we are reusing multiple resources at this point, I think it makes sense to leave the resx in. I will update the typo in the resource string mentioned.

**Comment by jskeet** [comment]
Righto, no problem.
