### ISSUE TITLE
JsonEventFormatter UriFormatException with relative Uris

### ISSUE THREAD

**Issue by Neuroglia** [cloudevents/sdk-csharp#93]
Hello,

When attempting to materialize a CloudEvent from a KafkaCloudEventMessage, I get an UriFormatException regarding the source attribute not being able to be constructed.

**UriFormatException: Invalid URI: The format of the URI could not be determined.**

I believe it has to do with the source Uri supplied as my original CloudEvent, which is relative.

Now the [1.0 spec](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#source-1), recommends using absolute uris for the source attribute, but it does not forbid using relative ones. 

Therefore, shouldn't the JsonEventFormatter be able to handle relative uris too?

### How to reproduce

```c#
var formatter = new JsonEventFormatter();
var e = new CloudEvent("test", new Uri("/source/test", UriKind.RelativeOrAbsolute))
{
    DataContentType = new ContentType(MediaTypeNames.Application.Octet),
    Data = Encoding.UTF8.GetBytes("Hello, world!")
};
var kafkaMessage = new KafkaCloudEventMessage(e, ContentMode.Binary, formatter);
e = kafkaMessage.ToCloudEvent(formatter);
```

**Comment by jskeet** [comment]
Indeed it should. I've very recently merged a massive overhaul of the whole codebase - I'll check that JsonEventFormatter handles this.

Do you have a full stack trace, by the way?

**Comment by jskeet** [comment]
I've validated that this works with the current (merged but not released) code, so I'll close this issue now. Please add a comment if you'd like it to be reopened.
